// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetSessionMetrics(arg1) {
  return window['go']['main']['App']['GetSessionMetrics'](arg1);
}

export function ListHistory() {
  return window['go']['main']['App']['ListHistory']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function LocalDelete(arg1) {
  return window['go']['main']['App']['LocalDelete'](arg1);
}

export function LocalListDir(arg1) {
  return window['go']['main']['App']['LocalListDir'](arg1);
}

export function LocalMkdir(arg1) {
  return window['go']['main']['App']['LocalMkdir'](arg1);
}

export function LocalParent(arg1) {
  return window['go']['main']['App']['LocalParent'](arg1);
}

export function LocalRename(arg1, arg2) {
  return window['go']['main']['App']['LocalRename'](arg1, arg2);
}

export function PickDir() {
  return window['go']['main']['App']['PickDir']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function ReadHistory(arg1) {
  return window['go']['main']['App']['ReadHistory'](arg1);
}

export function SaveSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveSession'](arg1, arg2, arg3, arg4, arg5);
}

export function SftpChmod(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpChmod'](arg1, arg2, arg3);
}

export function SftpDelete(arg1, arg2) {
  return window['go']['main']['App']['SftpDelete'](arg1, arg2);
}

export function SftpDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpDownload'](arg1, arg2, arg3, arg4);
}

export function SftpListDir(arg1, arg2) {
  return window['go']['main']['App']['SftpListDir'](arg1, arg2);
}

export function SftpMkdir(arg1, arg2) {
  return window['go']['main']['App']['SftpMkdir'](arg1, arg2);
}

export function SftpPwd(arg1) {
  return window['go']['main']['App']['SftpPwd'](arg1);
}

export function SftpRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpRename'](arg1, arg2, arg3);
}

export function SftpTasks() {
  return window['go']['main']['App']['SftpTasks']();
}

export function SftpUpload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpUpload'](arg1, arg2, arg3, arg4);
}

export function SshClose(arg1) {
  return window['go']['main']['App']['SshClose'](arg1);
}

export function SshKeepAlive(arg1) {
  return window['go']['main']['App']['SshKeepAlive'](arg1);
}

export function SshResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SshResize'](arg1, arg2, arg3);
}

export function SshSend(arg1, arg2) {
  return window['go']['main']['App']['SshSend'](arg1, arg2);
}
