// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptHostKey(arg1, arg2) {
  return window['go']['main']['App']['AcceptHostKey'](arg1, arg2);
}

export function AiCancel() {
  return window['go']['main']['App']['AiCancel']();
}

export function AiChat(arg1, arg2) {
  return window['go']['main']['App']['AiChat'](arg1, arg2);
}

export function AiConfigure(arg1, arg2, arg3) {
  return window['go']['main']['App']['AiConfigure'](arg1, arg2, arg3);
}

export function AiSetKey(arg1) {
  return window['go']['main']['App']['AiSetKey'](arg1);
}

export function AiStatus() {
  return window['go']['main']['App']['AiStatus']();
}

export function ApplyUpdate(arg1, arg2) {
  return window['go']['main']['App']['ApplyUpdate'](arg1, arg2);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearAlerts() {
  return window['go']['main']['App']['ClearAlerts']();
}

export function ClearAudit() {
  return window['go']['main']['App']['ClearAudit']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteCredential(arg1) {
  return window['go']['main']['App']['DeleteCredential'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function EditRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['EditRemoteFile'](arg1, arg2);
}

export function EditorLoadRemote(arg1, arg2) {
  return window['go']['main']['App']['EditorLoadRemote'](arg1, arg2);
}

export function EditorSaveLocal(arg1, arg2) {
  return window['go']['main']['App']['EditorSaveLocal'](arg1, arg2);
}

export function EditorSaveRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditorSaveRemote'](arg1, arg2, arg3);
}

export function GetAlertConfig() {
  return window['go']['main']['App']['GetAlertConfig']();
}

export function GetDiskUsage(arg1) {
  return window['go']['main']['App']['GetDiskUsage'](arg1);
}

export function GetOpenPorts(arg1) {
  return window['go']['main']['App']['GetOpenPorts'](arg1);
}

export function GetProcessList(arg1) {
  return window['go']['main']['App']['GetProcessList'](arg1);
}

export function GetSessionMetrics(arg1) {
  return window['go']['main']['App']['GetSessionMetrics'](arg1);
}

export function GetSysMetrics(arg1) {
  return window['go']['main']['App']['GetSysMetrics'](arg1);
}

export function GetSysMetricsHistory(arg1) {
  return window['go']['main']['App']['GetSysMetricsHistory'](arg1);
}

export function LaunchRdp(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchRdp'](arg1, arg2, arg3);
}

export function LaunchVnc(arg1, arg2) {
  return window['go']['main']['App']['LaunchVnc'](arg1, arg2);
}

export function ListAlerts() {
  return window['go']['main']['App']['ListAlerts']();
}

export function ListAudit() {
  return window['go']['main']['App']['ListAudit']();
}

export function ListCredentials() {
  return window['go']['main']['App']['ListCredentials']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListHistory() {
  return window['go']['main']['App']['ListHistory']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListSnippets() {
  return window['go']['main']['App']['ListSnippets']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function ListTunnels() {
  return window['go']['main']['App']['ListTunnels']();
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function LocalDelete(arg1) {
  return window['go']['main']['App']['LocalDelete'](arg1);
}

export function LocalListDir(arg1) {
  return window['go']['main']['App']['LocalListDir'](arg1);
}

export function LocalMkdir(arg1) {
  return window['go']['main']['App']['LocalMkdir'](arg1);
}

export function LocalParent(arg1) {
  return window['go']['main']['App']['LocalParent'](arg1);
}

export function LocalRename(arg1, arg2) {
  return window['go']['main']['App']['LocalRename'](arg1, arg2);
}

export function MoveSession(arg1, arg2) {
  return window['go']['main']['App']['MoveSession'](arg1, arg2);
}

export function PickDir() {
  return window['go']['main']['App']['PickDir']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function ReadCommandLog(arg1) {
  return window['go']['main']['App']['ReadCommandLog'](arg1);
}

export function ReadHistory(arg1) {
  return window['go']['main']['App']['ReadHistory'](arg1);
}

export function SaveAlertConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveAlertConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveCredential(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveCredential'](arg1, arg2, arg3, arg4);
}

export function SaveSession(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['SaveSession'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function SaveSnippet(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSnippet'](arg1, arg2, arg3);
}

export function SaveTask(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveTask'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SearchHistory(arg1) {
  return window['go']['main']['App']['SearchHistory'](arg1);
}

export function SessionMeta(arg1) {
  return window['go']['main']['App']['SessionMeta'](arg1);
}

export function SftpChmod(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpChmod'](arg1, arg2, arg3);
}

export function SftpDelete(arg1, arg2) {
  return window['go']['main']['App']['SftpDelete'](arg1, arg2);
}

export function SftpDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpDownload'](arg1, arg2, arg3, arg4);
}

export function SftpListDir(arg1, arg2) {
  return window['go']['main']['App']['SftpListDir'](arg1, arg2);
}

export function SftpMkdir(arg1, arg2) {
  return window['go']['main']['App']['SftpMkdir'](arg1, arg2);
}

export function SftpPwd(arg1) {
  return window['go']['main']['App']['SftpPwd'](arg1);
}

export function SftpRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpRename'](arg1, arg2, arg3);
}

export function SftpTasks() {
  return window['go']['main']['App']['SftpTasks']();
}

export function SftpUpload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpUpload'](arg1, arg2, arg3, arg4);
}

export function SshClose(arg1) {
  return window['go']['main']['App']['SshClose'](arg1);
}

export function SshKeepAlive(arg1) {
  return window['go']['main']['App']['SshKeepAlive'](arg1);
}

export function SshResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SshResize'](arg1, arg2, arg3);
}

export function SshSend(arg1, arg2) {
  return window['go']['main']['App']['SshSend'](arg1, arg2);
}

export function StartTunnel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartTunnel'](arg1, arg2, arg3, arg4);
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function SyncListDevices(arg1) {
  return window['go']['main']['App']['SyncListDevices'](arg1);
}

export function SyncLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncLogin'](arg1, arg2, arg3);
}

export function SyncPull(arg1, arg2) {
  return window['go']['main']['App']['SyncPull'](arg1, arg2);
}

export function SyncPush(arg1, arg2) {
  return window['go']['main']['App']['SyncPush'](arg1, arg2);
}

export function SyncRegister(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SyncRegister'](arg1, arg2, arg3, arg4);
}

export function SyncRevokeDevice(arg1, arg2) {
  return window['go']['main']['App']['SyncRevokeDevice'](arg1, arg2);
}

export function TestAlert(arg1) {
  return window['go']['main']['App']['TestAlert'](arg1);
}

export function VaultExport(arg1) {
  return window['go']['main']['App']['VaultExport'](arg1);
}

export function VaultImport(arg1, arg2) {
  return window['go']['main']['App']['VaultImport'](arg1, arg2);
}

export function VncClose(arg1) {
  return window['go']['main']['App']['VncClose'](arg1);
}

export function VncConnect(arg1, arg2, arg3) {
  return window['go']['main']['App']['VncConnect'](arg1, arg2, arg3);
}

export function VncKeyEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['VncKeyEvent'](arg1, arg2, arg3);
}

export function VncPointerEvent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['VncPointerEvent'](arg1, arg2, arg3, arg4);
}
