// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Connect(arg1:model.SshConfig):Promise<number>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetSessionMetrics(arg1:number):Promise<model.Metrics>;

export function GetSysMetrics(arg1:number):Promise<model.SysMetrics>;

export function LaunchRdp(arg1:string,arg2:number,arg3:string):Promise<void>;

export function ListHistory():Promise<Array<model.HistoryEntry>>;

export function ListSessions():Promise<Array<model.StoredSession>>;

export function ListTunnels():Promise<Array<model.Tunnel>>;

export function LoadSession(arg1:string):Promise<model.SshConfig>;

export function LocalDelete(arg1:string):Promise<void>;

export function LocalListDir(arg1:string):Promise<Array<model.FileEntry>>;

export function LocalMkdir(arg1:string):Promise<void>;

export function LocalParent(arg1:string):Promise<string>;

export function LocalRename(arg1:string,arg2:string):Promise<void>;

export function PickDir():Promise<string>;

export function PickFile():Promise<string>;

export function ReadHistory(arg1:string):Promise<string>;

export function SaveSession(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<string>;

export function SftpChmod(arg1:number,arg2:string,arg3:number):Promise<void>;

export function SftpDelete(arg1:number,arg2:string):Promise<void>;

export function SftpDownload(arg1:number,arg2:string,arg3:string,arg4:string):Promise<number>;

export function SftpListDir(arg1:number,arg2:string):Promise<Array<model.FileEntry>>;

export function SftpMkdir(arg1:number,arg2:string):Promise<void>;

export function SftpPwd(arg1:number):Promise<string>;

export function SftpRename(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SftpTasks():Promise<Array<model.TransferTask>>;

export function SftpUpload(arg1:number,arg2:string,arg3:string,arg4:string):Promise<number>;

export function SshClose(arg1:number):Promise<void>;

export function SshKeepAlive(arg1:number):Promise<number>;

export function SshResize(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SshSend(arg1:number,arg2:string):Promise<void>;

export function StartTunnel(arg1:number,arg2:string,arg3:number,arg4:string):Promise<number>;

export function StopTunnel(arg1:number):Promise<void>;
