// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AcceptHostKey(arg1:string,arg2:number):Promise<void>;

export function AiCancel():Promise<void>;

export function AiChat(arg1:number,arg2:string):Promise<void>;

export function AiConfigure(arg1:string,arg2:string,arg3:number):Promise<void>;

export function AiSetKey(arg1:string):Promise<void>;

export function AiStatus():Promise<model.AiStatus>;

export function ClearAudit():Promise<void>;

export function Connect(arg1:model.SshConfig):Promise<number>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSnippet(arg1:string):Promise<void>;

export function EditRemoteFile(arg1:number,arg2:string):Promise<void>;

export function EditorLoadRemote(arg1:number,arg2:string):Promise<string>;

export function EditorSaveLocal(arg1:string,arg2:string):Promise<void>;

export function EditorSaveRemote(arg1:number,arg2:string,arg3:string):Promise<void>;

export function GetDiskUsage(arg1:number):Promise<Array<model.DiskUsage>>;

export function GetOpenPorts(arg1:number):Promise<Array<model.PortInfo>>;

export function GetProcessList(arg1:number):Promise<Array<model.ProcEntry>>;

export function GetSessionMetrics(arg1:number):Promise<model.Metrics>;

export function GetSysMetrics(arg1:number):Promise<model.SysMetrics>;

export function GetSysMetricsHistory(arg1:number):Promise<Array<model.SysMetrics>>;

export function LaunchRdp(arg1:string,arg2:number,arg3:string):Promise<void>;

export function ListAudit():Promise<Array<model.AuditEntry>>;

export function ListGroups():Promise<Array<string>>;

export function ListHistory():Promise<Array<model.HistoryEntry>>;

export function ListSessions():Promise<Array<model.StoredSession>>;

export function ListSnippets():Promise<Array<model.Snippet>>;

export function ListTunnels():Promise<Array<model.Tunnel>>;

export function LoadSession(arg1:string):Promise<model.SshConfig>;

export function LocalDelete(arg1:string):Promise<void>;

export function LocalListDir(arg1:string):Promise<Array<model.FileEntry>>;

export function LocalMkdir(arg1:string):Promise<void>;

export function LocalParent(arg1:string):Promise<string>;

export function LocalRename(arg1:string,arg2:string):Promise<void>;

export function MoveSession(arg1:string,arg2:string):Promise<void>;

export function PickDir():Promise<string>;

export function PickFile():Promise<string>;

export function ReadHistory(arg1:string):Promise<string>;

export function SaveSession(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:number,arg11:string,arg12:string):Promise<string>;

export function SaveSnippet(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SearchHistory(arg1:string):Promise<Array<model.HistoryMatch>>;

export function SftpChmod(arg1:number,arg2:string,arg3:number):Promise<void>;

export function SftpDelete(arg1:number,arg2:string):Promise<void>;

export function SftpDownload(arg1:number,arg2:string,arg3:string,arg4:string):Promise<number>;

export function SftpListDir(arg1:number,arg2:string):Promise<Array<model.FileEntry>>;

export function SftpMkdir(arg1:number,arg2:string):Promise<void>;

export function SftpPwd(arg1:number):Promise<string>;

export function SftpRename(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SftpTasks():Promise<Array<model.TransferTask>>;

export function SftpUpload(arg1:number,arg2:string,arg3:string,arg4:string):Promise<number>;

export function SshClose(arg1:number):Promise<void>;

export function SshKeepAlive(arg1:number):Promise<number>;

export function SshResize(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SshSend(arg1:number,arg2:string):Promise<void>;

export function StartTunnel(arg1:number,arg2:string,arg3:number,arg4:string):Promise<number>;

export function StopTunnel(arg1:number):Promise<void>;
