// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SshClose(arg1:number):Promise<void>;

export function SshConnect(arg1:main.SshConfig):Promise<number>;

export function SshResize(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SshSend(arg1:number,arg2:string):Promise<void>;
